{
  "hash": "f698eb34f550711d8b9c1d44b57ca199",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bikeshare_SpaceTime_Prediction\"\nsubtitle: \"CPLN 5080 - Spring 2026\"\nauthor: \"Wil Rantala and Indrajeet Chavan\"\ndate: today\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n# INTRODUCTION\n\n## The Rebalancing Challenge in Philadelphia\n\nPhiladelphia's Indego bike share system faces the same operational challenge as every bike share system: **rebalancing bikes to meet anticipated demand**.\n\nImagine you're an Indego operations manager at 6:00 AM on a Monday morning. You have: - 200 stations across Philadelphia - Limited trucks and staff for moving bikes - 2-3 hours before morning rush hour demand peaks - **The question:** Which stations will run out of bikes by 8:30 AM?\n\nThis lab will teach you to build predictive models that forecast bike share demand across **space** (different stations) and **time** (different hours) to help solve this operational problem.\n\n## Learning Objectives\n\nBy the end of this assignment, you will be able to:\n\n1.  **Understand panel data structure** for space-time analysis\n2.  **Create temporal lag variables** to capture demand persistence\n3.  **Build multiple predictive models** with increasing complexity\n4.  **Validate models temporally** (train on past, test on future)\n5.  **Analyze prediction errors** in both space and time\n6.  **Engineer new features** based on error patterns\n7.  **Critically evaluate** when prediction errors matter most\n\n## Before this assignment\n\nIn an in class assignment, we ran code on Q1 2025 Indego data which we will use to compare to the Q2 results in this lab. The Q1 and Q2 analysis will be done in the same environment, so we will specify the variables in this analysis by adding a Q2 to the end of the names, as to avoid potential mistakes where Q1 data is called in operations meant for Q2.\n\n# SET UP\n\n## Load Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\nlibrary(sf)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(riem)  # For Philadelphia weather from ASOS stations\n\nlibrary(viridis) # color scales for visualization\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(patchwork)\n\n\nlibrary(here)\noptions(scipen = 999) # Get rid of scientific notation to make it look tidier\n```\n:::\n\n\n## Create a consistent theme for maps and other renderings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotTheme <- theme_minimal() +\n  theme(\n    plot.title    = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption  = element_text(size = 8),\n    axis.text.x   = element_text(size = 10, angle = 45, hjust = 1),\n    axis.text.y   = element_text(size = 10),\n    axis.title    = element_text(size = 11, face = \"bold\"),\n    panel.grid.major = element_line(colour = \"#D0D0D0\", linewidth = 0.2),\n    panel.grid.minor = element_blank(),\n    axis.ticks    = element_blank(),\n    legend.position = \"right\"\n  )\n\nmapTheme <- theme_void() +\n  theme(\n    plot.title    = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption  = element_text(size = 8),\n    legend.position  = \"right\",\n    plot.margin      = margin(1, 1, 1, 1, \"cm\"),\n    legend.key.height = unit(1, \"cm\"),\n    legend.key.width  = unit(0.2, \"cm\")\n  )\n\npalette5 <- c(\"#eff3ff\", \"#bdd7e7\", \"#6baed6\", \"#3182bd\", \"#08519c\")\n```\n:::\n\n\n# Part 1: Import and Prep Data\n\n## Load Indego Trip Data (Q2 2025)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read Q2 2025 data\nindegoQ2 <- read_csv(\"Data/indego-trips-2025-q2.csv\")\n\n# Quick look at the data\nglimpse(indegoQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 365,760\nColumns: 15\n$ trip_id             <dbl> 1164246461, 1164246634, 1164246553, 1164246521, 11…\n$ duration            <dbl> 11, 31, 9, 3, 11, 7, 13, 12, 3, 58, 21, 5, 15, 10,…\n$ start_time          <chr> \"4/1/2025 0:04\", \"4/1/2025 0:04\", \"4/1/2025 0:17\",…\n$ end_time            <chr> \"4/1/2025 0:15\", \"4/1/2025 0:35\", \"4/1/2025 0:26\",…\n$ start_station       <dbl> 3022, 3040, 3396, 3054, 3280, 3301, 3158, 3374, 33…\n$ start_lat           <dbl> 39.95472, 39.96289, 39.92327, 39.96250, 39.93968, …\n$ start_lon           <dbl> -75.18323, -75.16606, -75.18210, -75.17420, -75.21…\n$ end_station         <dbl> 3064, 3100, 3349, 3235, 3349, 3051, 3028, 3154, 33…\n$ end_lat             <dbl> 39.93840, 39.92777, 39.93651, 39.96000, 39.93651, …\n$ end_lon             <dbl> -75.17327, -75.15103, -75.18621, -75.16510, -75.18…\n$ bike_id             <chr> \"31751\", \"14481\", \"02724\", \"24841\", \"25744\", \"3123…\n$ plan_duration       <dbl> 30, 30, 30, 365, 30, 365, 1, 30, 30, 30, 30, 30, 1…\n$ trip_route_category <chr> \"One Way\", \"One Way\", \"One Way\", \"One Way\", \"One W…\n$ passholder_type     <chr> \"Indego30\", \"Indego30\", \"Indego30\", \"Indego365\", \"…\n$ bike_type           <chr> \"electric\", \"standard\", \"standard\", \"electric\", \"e…\n```\n\n\n:::\n:::\n\n\n## Examine the Data Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many trips?\ncat(\"Total trips in Q2 2025:\", nrow(indegoQ2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal trips in Q2 2025: 365760 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Date range\ncat(\"Date range:\", \n    min(mdy_hm(indegoQ2$start_time)), \"to\", \n    max(mdy_hm(indegoQ2$start_time)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDate range: 1743465840 to 1751327820 \n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique stations?\ncat(\"Unique start stations:\", length(unique(indegoQ2$start_station)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique start stations: 273 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Trip types\ntable(indegoQ2$trip_route_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   One Way Round Trip \n    341060      24700 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Passholder types\ntable(indegoQ2$passholder_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  Day Pass   Indego30  Indego365 IndegoFlex       NULL    Walk-up \n     15712     189135     132693          1          4      28215 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Bike types\ntable(indegoQ2$bike_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nelectric standard \n  234502   131258 \n```\n\n\n:::\n:::\n\n\n## Create Time Bins\n\nWe need to aggregate trips into hourly intervals for our panel data structure. Here we'll use the lubridate library.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindegoQ2 <- indegoQ2 %>%\n  mutate(\n    # Parse datetime\n    start_datetime = mdy_hm(start_time),\n    end_datetime = mdy_hm(end_time),\n    \n    # Create hourly bins\n    interval60 = floor_date(start_datetime, unit = \"hour\"),\n    \n    # Extract time features\n    week = week(interval60),\n    month = month(interval60, label = TRUE),\n    dotw = wday(interval60, label = TRUE),\n    hour = hour(interval60),\n    date = as.Date(interval60),\n    \n    # Create useful indicators\n    weekend = ifelse(dotw %in% c(\"Sat\", \"Sun\"), 1, 0),\n    rush_hour = ifelse(hour %in% c(7, 8, 9, 16, 17, 18), 1, 0)\n  )\n\n# Look at temporal features\nhead(indegoQ2 %>% select(start_datetime, interval60, week, dotw, hour, weekend))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  start_datetime      interval60           week dotw   hour weekend\n  <dttm>              <dttm>              <dbl> <ord> <int>   <dbl>\n1 2025-04-01 00:04:00 2025-04-01 00:00:00    13 Tue       0       0\n2 2025-04-01 00:04:00 2025-04-01 00:00:00    13 Tue       0       0\n3 2025-04-01 00:17:00 2025-04-01 00:00:00    13 Tue       0       0\n4 2025-04-01 00:20:00 2025-04-01 00:00:00    13 Tue       0       0\n5 2025-04-01 00:25:00 2025-04-01 00:00:00    13 Tue       0       0\n6 2025-04-01 00:40:00 2025-04-01 00:00:00    13 Tue       0       0\n```\n\n\n:::\n:::\n\n\n# Part 2: Exploratory Data Analysis of Indego Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Daily trip counts\ndaily_trips <- indegoQ2 %>%\n  group_by(date) %>%\n  summarize(trips = n())\n\nggplot(daily_trips, aes(x = date, y = trips)) +\n  geom_line(color = \"#3182bd\", linewidth = 1) +\n  geom_smooth(se = FALSE, color = \"red\", linetype = \"dashed\") +\n  labs(\n    title = \"Indego Daily Ridership - Q2 2025\",\n    subtitle = \"Spring demand patterns in Philadelphia\",\n    x = \"Date\",\n    y = \"Daily Trips\",\n    caption = \"Source: Indego bike share\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/trips_over_time-1.png){width=672}\n:::\n:::\n\n\nThe plot of Q2 Indego daily ridership shows an increase of ridership through May, then staying relatively stable but still increasing slightly through the end of June. The lowest \"valleys\" are in April and May, and the highest peaks are in June. The sporadic up-and-down pattern reflects high weekday ridership and lower weekend ridership, attributed to high commuter ridership. The lowest day for ridership appears to be around April 11, when Philadelphia saw the intense rainfall for that month.\n\nLet's investigate...compare April 11th to all other Friday's in the data...what do we find?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrainy_day <- daily_trips %>% filter(date == \"2025-04-11\")\n\ntypical_boring_friday <- indegoQ2 %>%\n  filter(dotw == \"Fri\", date != \"2025-04-11\") %>%\n  group_by(date) %>%\n  summarize(trips = n()) %>%\n  summarize(avg_friday_trips = mean(trips))\n\nprint(rainy_day)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  date       trips\n  <date>     <int>\n1 2025-04-11  1289\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(typical_boring_friday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  avg_friday_trips\n             <dbl>\n1            4455.\n```\n\n\n:::\n:::\n\n\nOn Friday April 11th, there were 1289 rides, compared to an average of 4455 on other spring Fridays. It appears rain might be a good feature to include later in our analysis.\n\n## Hourly Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average trips by hour and day type\nhourly_patterns <- indegoQ2 %>%\n  group_by(hour, weekend) %>%\n  summarize(avg_trips = n() / n_distinct(date)) %>%\n  mutate(day_type = ifelse(weekend == 1, \"Weekend\", \"Weekday\"))\n\nggplot(hourly_patterns, aes(x = hour, y = avg_trips, color = day_type)) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"Weekday\" = \"#08519c\", \"Weekend\" = \"#6baed6\")) +\n  labs(\n    title = \"Average Hourly Ridership Patterns\",\n    subtitle = \"Clear commute patterns on weekdays\",\n    x = \"Hour of Day\",\n    y = \"Average Trips per Hour\",\n    color = \"Day Type\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/hourly_patterns-1.png){width=672}\n:::\n:::\n\n\nWeekdays have two peaks. The first, smaller peak is between 7am and 9am with a max average of just over 300 trips/hr aroud 8am. The second, greater peak is between 4pm and 7pm, with a max average of over 450 trips/hr around 5pm.\n\nWeekends, on the other hand, have a plateau'd peak from 12pm until around 6pm, staying consistent around 260 trips/hr.\n\nThe dual peak pattern for weekdays reflects the morning commute rush and much greater PM after-work rush when many go home, go shopping, or travel to recreational activities. The plateau peak of trips on weekends reflects the less work-oriented travel patterns of Philadelphia on weekends.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Most popular origin stations\ntop_stations <- indegoQ2 %>%\n  count(start_station, start_lat, start_lon, name = \"trips\") %>%\n  arrange(desc(trips)) %>%\n  head(20)\n\nkable(top_stations, \n      caption = \"Top 20 Indego Stations by Trip Origins\",\n      format.args = list(big.mark = \",\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Top 20 Indego Stations by Trip Origins</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> start_station </th>\n   <th style=\"text-align:right;\"> start_lat </th>\n   <th style=\"text-align:right;\"> start_lon </th>\n   <th style=\"text-align:right;\"> trips </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 3,010 </td>\n   <td style=\"text-align:right;\"> 39.94711 </td>\n   <td style=\"text-align:right;\"> -75.16618 </td>\n   <td style=\"text-align:right;\"> 6,278 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,032 </td>\n   <td style=\"text-align:right;\"> 39.94527 </td>\n   <td style=\"text-align:right;\"> -75.17971 </td>\n   <td style=\"text-align:right;\"> 4,751 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,359 </td>\n   <td style=\"text-align:right;\"> 39.94888 </td>\n   <td style=\"text-align:right;\"> -75.16978 </td>\n   <td style=\"text-align:right;\"> 4,181 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,028 </td>\n   <td style=\"text-align:right;\"> 39.94061 </td>\n   <td style=\"text-align:right;\"> -75.14958 </td>\n   <td style=\"text-align:right;\"> 4,028 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,163 </td>\n   <td style=\"text-align:right;\"> 39.94974 </td>\n   <td style=\"text-align:right;\"> -75.18097 </td>\n   <td style=\"text-align:right;\"> 4,000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,020 </td>\n   <td style=\"text-align:right;\"> 39.94855 </td>\n   <td style=\"text-align:right;\"> -75.19007 </td>\n   <td style=\"text-align:right;\"> 3,946 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,185 </td>\n   <td style=\"text-align:right;\"> 39.95169 </td>\n   <td style=\"text-align:right;\"> -75.15888 </td>\n   <td style=\"text-align:right;\"> 3,914 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,066 </td>\n   <td style=\"text-align:right;\"> 39.94561 </td>\n   <td style=\"text-align:right;\"> -75.17348 </td>\n   <td style=\"text-align:right;\"> 3,899 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,022 </td>\n   <td style=\"text-align:right;\"> 39.95472 </td>\n   <td style=\"text-align:right;\"> -75.18323 </td>\n   <td style=\"text-align:right;\"> 3,856 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,054 </td>\n   <td style=\"text-align:right;\"> 39.96250 </td>\n   <td style=\"text-align:right;\"> -75.17420 </td>\n   <td style=\"text-align:right;\"> 3,767 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,161 </td>\n   <td style=\"text-align:right;\"> 39.95486 </td>\n   <td style=\"text-align:right;\"> -75.18091 </td>\n   <td style=\"text-align:right;\"> 3,629 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,362 </td>\n   <td style=\"text-align:right;\"> 39.94816 </td>\n   <td style=\"text-align:right;\"> -75.16226 </td>\n   <td style=\"text-align:right;\"> 3,552 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,063 </td>\n   <td style=\"text-align:right;\"> 39.94633 </td>\n   <td style=\"text-align:right;\"> -75.16980 </td>\n   <td style=\"text-align:right;\"> 3,516 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,213 </td>\n   <td style=\"text-align:right;\"> 39.93887 </td>\n   <td style=\"text-align:right;\"> -75.16663 </td>\n   <td style=\"text-align:right;\"> 3,332 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,059 </td>\n   <td style=\"text-align:right;\"> 39.96244 </td>\n   <td style=\"text-align:right;\"> -75.16121 </td>\n   <td style=\"text-align:right;\"> 3,320 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,012 </td>\n   <td style=\"text-align:right;\"> 39.94218 </td>\n   <td style=\"text-align:right;\"> -75.17747 </td>\n   <td style=\"text-align:right;\"> 3,264 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,007 </td>\n   <td style=\"text-align:right;\"> 39.94517 </td>\n   <td style=\"text-align:right;\"> -75.15993 </td>\n   <td style=\"text-align:right;\"> 3,242 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,061 </td>\n   <td style=\"text-align:right;\"> 39.95425 </td>\n   <td style=\"text-align:right;\"> -75.17761 </td>\n   <td style=\"text-align:right;\"> 3,193 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,101 </td>\n   <td style=\"text-align:right;\"> 39.94295 </td>\n   <td style=\"text-align:right;\"> -75.15955 </td>\n   <td style=\"text-align:right;\"> 3,170 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,296 </td>\n   <td style=\"text-align:right;\"> 39.95134 </td>\n   <td style=\"text-align:right;\"> -75.16758 </td>\n   <td style=\"text-align:right;\"> 3,088 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nTo put these stations on a map to get a better understanding of the spatial distribution of ridership, we're going to load in census tracts along with some demographic data.\n\n# Part 3: Put Data in Spatial Context\n\n## Load Philadelphia Census Data\n\nLet's load that census data in with some demographic data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get Philadelphia census tracts\nphilly_census <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    \"B01003_001\",  # Total population\n    \"B19013_001\",  # Median household income\n    \"B08301_001\",  # Total commuters\n    \"B08301_010\",  # Commute by transit\n    \"B02001_002\",  # White alone\n    \"B25077_001\"   # Median home value\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  geometry = TRUE,\n  output = \"wide\"\n) %>%\n  rename(\n    Total_Pop = B01003_001E,\n    Med_Inc = B19013_001E,\n    Total_Commuters = B08301_001E,\n    Transit_Commuters = B08301_010E,\n    White_Pop = B02001_002E,\n    Med_Home_Value = B25077_001E\n  ) %>%\n  mutate(\n    Percent_Taking_Transit = (Transit_Commuters / Total_Commuters) * 100,\n    Percent_White = (White_Pop / Total_Pop) * 100\n  ) %>%\n  st_transform(crs = 4326)  #transforming to WGS84 for lat/lon matching, currently in NAD83\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |==========================================                            |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the data\nglimpse(philly_census)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 408\nColumns: 17\n$ GEOID                  <chr> \"42101001500\", \"42101001800\", \"42101002802\", \"4…\n$ NAME                   <chr> \"Census Tract 15; Philadelphia County; Pennsylv…\n$ Total_Pop              <dbl> 3251, 3300, 5720, 4029, 4415, 1815, 3374, 2729,…\n$ B01003_001M            <dbl> 677, 369, 796, 437, 853, 210, 480, 734, 763, 11…\n$ Med_Inc                <dbl> 110859, 114063, 78871, 61583, 32347, 48581, 597…\n$ B19013_001M            <dbl> 24975, 30714, 20396, 22293, 4840, 13812, 6278, …\n$ Total_Commuters        <dbl> 2073, 2255, 3032, 2326, 1980, 969, 2427, 708, 2…\n$ B08301_001M            <dbl> 387, 308, 478, 383, 456, 189, 380, 281, 456, 68…\n$ Transit_Commuters      <dbl> 429, 123, 685, 506, 534, 192, 658, 218, 438, 51…\n$ B08301_010M            <dbl> 188, 66, 219, 144, 285, 71, 278, 184, 176, 235,…\n$ White_Pop              <dbl> 2185, 2494, 3691, 3223, 182, 984, 2111, 231, 35…\n$ B02001_002M            <dbl> 268, 381, 592, 380, 88, 190, 463, 112, 238, 778…\n$ Med_Home_Value         <dbl> 568300, 605000, 350600, 296400, 76600, 289700, …\n$ B25077_001M            <dbl> 58894, 34876, 12572, 22333, 10843, 118720, 1506…\n$ geometry               <MULTIPOLYGON [°]> MULTIPOLYGON (((-75.16558 3..., MU…\n$ Percent_Taking_Transit <dbl> 20.694645, 5.454545, 22.592348, 21.754084, 26.9…\n$ Percent_White          <dbl> 67.2100892, 75.5757576, 64.5279720, 79.9950360,…\n```\n\n\n:::\n:::\n\n\n## Map Philadelphia Context\n\nNow let's throw our Indego stations on a map of Philly\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Map median income\nggplot() +\n  geom_sf(data = philly_census, aes(fill = Med_Inc), color = NA) +\n  scale_fill_viridis(\n    option = \"viridis\",\n    name = \"Median\\nIncome\",\n    labels = scales::dollar\n  ) +\n  labs(\n    title = \"Philadelphia Median Household Income by Census Tract\",\n    subtitle = \"Context for understanding bike share demand patterns\"\n  ) +\n  # Stations \n  geom_point(\n    data = indegoQ2,\n    aes(x = start_lon, y = start_lat),\n    color = \"red\", size = 0.25, alpha = 0.6\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/map_philly-1.png){width=672}\n:::\n:::\n\n\nTo have the demographic and spatial context connected to our bike stations, let's spatially join the census and Indego data.\n\n## Join Census Data to Stations\n\nWe'll spatially join census characteristics to each bike station.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create sf object for stations\nstations_sfQ2 <- indegoQ2 %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  st_as_sf(coords = c(\"start_lon\", \"start_lat\"), crs = 4326)\n\n# Spatial join to get census tract for each station\nstations_censusQ2 <- st_join(stations_sfQ2, philly_census, left = TRUE) %>%\n  st_drop_geometry()\n\n# Look at the result - investigate whether all of the stations joined to census data -- according to the map above there are stations in non-residential tracts.\n\nstations_for_mapQ2 <- indegoQ2 %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  left_join(\n    stations_censusQ2 %>% select(start_station, Med_Inc),\n    by = \"start_station\"\n  ) %>%\n  mutate(has_census = !is.na(Med_Inc))\n\n# Add back to trip data\nindego_censusQ2 <- indegoQ2 %>%\n  left_join(\n    stations_censusQ2 %>% \n      select(start_station, Med_Inc, Percent_Taking_Transit, \n             Percent_White, Total_Pop),\n    by = \"start_station\"\n  )\n\n\n# Prepare data for visualization\nstations_for_mapQ2 <- indegoQ2 %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  left_join(\n    stations_censusQ2 %>% select(start_station, Med_Inc),\n    by = \"start_station\"\n  ) %>%\n  mutate(has_census = !is.na(Med_Inc))\n\n# Create the map showing problem stations\nggplot() +\n  geom_sf(data = philly_census, aes(fill = Med_Inc), color = \"white\", size = 0.1) +\n  scale_fill_viridis(\n    option = \"viridis\",\n    name = \"Median\\nIncome\",\n    labels = scales::dollar,\n    na.value = \"grey90\"\n  ) +\n  # Stations with census data (small grey dots)\n  geom_point(\n    data = stations_for_mapQ2 %>% filter(has_census),\n    aes(x = start_lon, y = start_lat),\n    color = \"grey30\", size = 1, alpha = 0.6\n  ) +\n  # Stations WITHOUT census data (red X marks the spot)\n  geom_point(\n    data = stations_for_mapQ2 %>% filter(!has_census),\n    aes(x = start_lon, y = start_lat),\n    color = \"red\", size = 1, shape = 4, stroke = 1.5\n  ) +\n  labs(\n    title = \"Philadelphia Median Household Income by Census Tract\",\n    subtitle = \"Indego stations shown (RED = no census data match)\",\n    caption = \"Red X marks indicate stations that didn't join to census tracts\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/join_census_to_stations-1.png){width=672}\n:::\n:::\n\n\nA handful of our bike stations aren't located in our census tracts. For this example, we are going to remove them -- this is not necessarily the right way to do things always, but for the sake of simplicity, we are narrowing our scope to only stations in residential neighborhoods. One might want to make a separate model entirely for non-residential bike stations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify which stations to keep\nvalid_stationsQ2 <- stations_censusQ2 %>%\n  filter(!is.na(Med_Inc)) %>%\n  pull(start_station)\n\n# Filter trip data to valid stations only\nindego_censusQ2 <- indegoQ2 %>%\n  filter(start_station %in% valid_stationsQ2) %>%\n  left_join(\n    stations_censusQ2 %>% \n      select(start_station, Med_Inc, Percent_Taking_Transit, \n             Percent_White, Total_Pop),\n    by = \"start_station\"\n  )\n```\n:::\n\n\n## Get Weather Data\n\nLet's get some weather data for Philly. We know it significantly affects bike ridership. Do you like biking to work in the rain?!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get weather from Philadelphia International Airport (KPHL)\n# This covers Q1 2025: January 1 - March 31\nweather_dataQ2 <- riem_measures(\n  station = \"PHL\",  # Philadelphia International Airport\n  date_start = \"2025-04-01\",\n  date_end = \"2025-06-30\"\n)\n\n# Process weather data\nweather_processedQ2 <- weather_dataQ2 %>%\n  mutate(\n    interval60 = floor_date(valid, unit = \"hour\"),\n    Temperature = tmpf,  # Temperature in Fahrenheit\n    Precipitation = ifelse(is.na(p01i), 0, p01i),  # Hourly precip in inches\n    Wind_Speed = sknt  # Wind speed in knots\n  ) %>%\n  select(interval60, Temperature, Precipitation, Wind_Speed) %>%\n  distinct(interval60, .keep_all = TRUE)\n\n# Check for missing hours and interpolate if needed\nweather_completeQ2 <- weather_processedQ2 %>%\n  complete(interval60 = seq(min(interval60), max(interval60), by = \"hour\")) %>%\n  fill(Temperature, Precipitation, Wind_Speed, .direction = \"down\")\n\n# Look at the weather\nsummary(weather_completeQ2 %>% select(Temperature, Precipitation, Wind_Speed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Temperature     Precipitation        Wind_Speed    \n Min.   : 33.00   Min.   :0.000000   Min.   : 0.000  \n 1st Qu.: 57.00   1st Qu.:0.000000   1st Qu.: 5.000  \n Median : 66.00   Median :0.000000   Median : 8.000  \n Mean   : 65.62   Mean   :0.002024   Mean   : 8.125  \n 3rd Qu.: 73.00   3rd Qu.:0.000000   3rd Qu.:11.000  \n Max.   :100.00   Max.   :0.590000   Max.   :27.000  \n```\n\n\n:::\n:::\n\n\n## Visualize Weather Patterns\n\nLet's look at Philly's springtime weather from 2025\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(weather_completeQ2, aes(x = interval60, y = Temperature)) +\n  geom_line(color = \"#3182bd\", alpha = 0.7) +\n  geom_smooth(se = FALSE, color = \"red\") +\n  labs(\n    title = \"Philadelphia Temperature - Q2 2025\",\n    subtitle = \"Spring to early Summer transition\",\n    x = \"Date\",\n    y = \"Temperature (°F)\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/visualize-weather-1.png){width=672}\n:::\n:::\n\n\nBeautiful springtime weather! Again, there's that April 11th dip. 45 degrees and rainy is no time to bike.\n\n# CREATE SPACE-TIME PANEL\n\nNow, let's create a space-time panel with our bike trip data.\n\n## Aggregate Trips to Station-Hour Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count trips by station-hour\ntrips_panelQ2 <- indego_censusQ2 %>%\n  group_by(interval60, start_station, start_lat, start_lon,\n           Med_Inc, Percent_Taking_Transit, Percent_White, Total_Pop) %>%\n  summarize(Trip_Count = n()) %>%\n  ungroup()\n\n# How many station-hour observations?\nnrow(trips_panelQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 179107\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique stations?\nlength(unique(trips_panelQ2$start_station))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 252\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique hours?\nlength(unique(trips_panelQ2$interval60))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2177\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(trips_panelQ2$Trip_Count)\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/aggregate-trips-1.png){width=672}\n:::\n:::\n\n\nThere are a lot of zeros -- many stations will have 0 trips in a given hour\n\n## Create Complete Panel Structure\n\nNot every station has trips every hour. We need a **complete panel** where every station-hour combination exists (even if Trip_Count = 0).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate expected panel size\nn_stationsQ2 <- length(unique(trips_panelQ2$start_station))\nn_hoursQ2 <- length(unique(trips_panelQ2$interval60))\nexpected_rowsQ2 <- n_stationsQ2 * n_hoursQ2\n\ncat(\"Expected panel rows:\", format(expected_rowsQ2, big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected panel rows: 548,604 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Current rows:\", format(nrow(trips_panelQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurrent rows: 179,107 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing rows:\", format(expected_rowsQ2 - nrow(trips_panelQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing rows: 369,497 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Create complete panel\nstudy_panelQ2 <- expand_grid(\n  interval60 = unique(trips_panelQ2$interval60),\n  start_station = unique(trips_panelQ2$start_station)\n) %>%\n  # Join trip counts\n  left_join(trips_panelQ2 %>% \n              select(interval60, start_station, Trip_Count),\n            by = c(\"interval60\", \"start_station\")) %>%\n  # Replace NA trip counts with 0\n  mutate(Trip_Count = replace_na(Trip_Count, 0))\n\nglimpse(study_panelQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 548,604\nColumns: 3\n$ interval60    <dttm> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01, 2025-04…\n$ start_station <dbl> 3022, 3040, 3054, 3280, 3301, 3396, 3158, 3371, 3374, 30…\n$ Trip_Count    <int> 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(study_panelQ2$Trip_Count)\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/complete-panel-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Fill in station attributes (they're the same for all hours)\nstation_attributesQ2 <- trips_panelQ2 %>%\n  group_by(start_station) %>%\n  summarize(\n    start_lat = first(start_lat),\n    start_lon = first(start_lon),\n    Med_Inc = first(Med_Inc),\n    Percent_Taking_Transit = first(Percent_Taking_Transit),\n    Percent_White = first(Percent_White),\n    Total_Pop = first(Total_Pop)\n  )\n\nglimpse(station_attributesQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 252\nColumns: 7\n$ start_station          <dbl> 3005, 3006, 3007, 3008, 3009, 3010, 3012, 3014,…\n$ start_lat              <dbl> 39.94733, 39.95220, 39.94517, 39.98081, 39.9557…\n$ start_lon              <dbl> -75.14403, -75.20311, -75.15993, -75.15067, -75…\n$ Med_Inc                <dbl> 144922, 21064, 58557, 22244, 37674, 88583, 1385…\n$ Percent_Taking_Transit <dbl> 11.742827, 9.418565, 11.401515, 27.430556, 10.8…\n$ Percent_White          <dbl> 86.29640, 46.88109, 62.85341, 39.65227, 60.2169…\n$ Total_Pop              <dbl> 3583, 6156, 4598, 5349, 7375, 3134, 3643, 3914,…\n```\n\n\n:::\n\n```{.r .cell-code}\nstudy_panelQ2 <- study_panelQ2 %>%\n  left_join(station_attributesQ2, by = \"start_station\")\n\nglimpse(study_panelQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 548,604\nColumns: 9\n$ interval60             <dttm> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01…\n$ start_station          <dbl> 3022, 3040, 3054, 3280, 3301, 3396, 3158, 3371,…\n$ Trip_Count             <int> 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ start_lat              <dbl> 39.95472, 39.96289, 39.96250, 39.93968, 39.9502…\n$ start_lon              <dbl> -75.18323, -75.16606, -75.17420, -75.21362, -75…\n$ Med_Inc                <dbl> 29464, 79694, 88936, 39547, 86809, 49493, 61583…\n$ Percent_Taking_Transit <dbl> 5.081301, 14.574899, 11.852149, 25.837629, 25.9…\n$ Percent_White          <dbl> 54.396043, 61.073826, 60.379375, 9.203540, 79.6…\n$ Total_Pop              <dbl> 6267, 2235, 3743, 3955, 1807, 3742, 4029, 3486,…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verify we have complete panel\ncat(\"Complete panel rows:\", format(nrow(study_panelQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComplete panel rows: 548,604 \n```\n\n\n:::\n:::\n\n\n## Add Time Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panelQ2 <- study_panelQ2 %>%\n  mutate(\n    week = week(interval60),\n    month = month(interval60, label = TRUE),\n    dotw = wday(interval60, label = TRUE),\n    hour = hour(interval60),\n    date = as.Date(interval60),\n    weekend = ifelse(dotw %in% c(\"Sat\", \"Sun\"), 1, 0),\n    rush_hour = ifelse(hour %in% c(7, 8, 9, 16, 17, 18), 1, 0)\n  )\n\nglimpse(study_panelQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 548,604\nColumns: 16\n$ interval60             <dttm> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01…\n$ start_station          <dbl> 3022, 3040, 3054, 3280, 3301, 3396, 3158, 3371,…\n$ Trip_Count             <int> 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ start_lat              <dbl> 39.95472, 39.96289, 39.96250, 39.93968, 39.9502…\n$ start_lon              <dbl> -75.18323, -75.16606, -75.17420, -75.21362, -75…\n$ Med_Inc                <dbl> 29464, 79694, 88936, 39547, 86809, 49493, 61583…\n$ Percent_Taking_Transit <dbl> 5.081301, 14.574899, 11.852149, 25.837629, 25.9…\n$ Percent_White          <dbl> 54.396043, 61.073826, 60.379375, 9.203540, 79.6…\n$ Total_Pop              <dbl> 6267, 2235, 3743, 3955, 1807, 3742, 4029, 3486,…\n$ week                   <dbl> 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,…\n$ month                  <ord> Apr, Apr, Apr, Apr, Apr, Apr, Apr, Apr, Apr, Ap…\n$ dotw                   <ord> Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tu…\n$ hour                   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ date                   <date> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01…\n$ weekend                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ rush_hour              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\n## Join Weather Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panelQ2 <- study_panelQ2 %>%\n  left_join(weather_completeQ2, by = \"interval60\")\n\nglimpse(study_panelQ2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 548,604\nColumns: 19\n$ interval60             <dttm> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01…\n$ start_station          <dbl> 3022, 3040, 3054, 3280, 3301, 3396, 3158, 3371,…\n$ Trip_Count             <int> 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ start_lat              <dbl> 39.95472, 39.96289, 39.96250, 39.93968, 39.9502…\n$ start_lon              <dbl> -75.18323, -75.16606, -75.17420, -75.21362, -75…\n$ Med_Inc                <dbl> 29464, 79694, 88936, 39547, 86809, 49493, 61583…\n$ Percent_Taking_Transit <dbl> 5.081301, 14.574899, 11.852149, 25.837629, 25.9…\n$ Percent_White          <dbl> 54.396043, 61.073826, 60.379375, 9.203540, 79.6…\n$ Total_Pop              <dbl> 6267, 2235, 3743, 3955, 1807, 3742, 4029, 3486,…\n$ week                   <dbl> 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,…\n$ month                  <ord> Apr, Apr, Apr, Apr, Apr, Apr, Apr, Apr, Apr, Ap…\n$ dotw                   <ord> Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tu…\n$ hour                   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ date                   <date> 2025-04-01, 2025-04-01, 2025-04-01, 2025-04-01…\n$ weekend                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ rush_hour              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ Temperature            <dbl> 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71,…\n$ Precipitation          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ Wind_Speed             <dbl> 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check for missing values\nsummary(study_panelQ2 %>% select(Trip_Count, Temperature, Precipitation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Trip_Count       Temperature     Precipitation  \n Min.   : 0.0000   Min.   : 33.00   Min.   :0.000  \n 1st Qu.: 0.0000   1st Qu.: 57.00   1st Qu.:0.000  \n Median : 0.0000   Median : 66.00   Median :0.000  \n Mean   : 0.6266   Mean   : 65.64   Mean   :0.002  \n 3rd Qu.: 1.0000   3rd Qu.: 74.00   3rd Qu.:0.000  \n Max.   :27.0000   Max.   :100.00   Max.   :0.590  \n                   NA's   :6048     NA's   :6048   \n```\n\n\n:::\n:::\n\n\n# CREATE TEMPORAL LAG VARIABLES\n\nThe key innovation for space-time prediction: **past demand predicts future demand**.\n\n## Why Temporal Lags?\n\nIf there were 15 bike trips from Station A at 8:00 AM, there will probably be \\~15 trips at 9:00 AM. We can use this temporal persistence to improve predictions.\n\n**Note:** We still can't use spatial lags in prediction. Temporal lags are different because time moves in one direction - past predicts the future, but the future does not predict the past. Spatial lags are non-directional and create circular prediction logic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort by station and time\nstudy_panelQ2 <- study_panelQ2 %>%\n  arrange(start_station, interval60)\n\n# Create lag variables WITHIN each station\nstudy_panelQ2 <- study_panelQ2 %>%\n  group_by(start_station) %>%\n  mutate(\n    lag1Hour = lag(Trip_Count, 1),\n    lag2Hours = lag(Trip_Count, 2),\n    lag3Hours = lag(Trip_Count, 3),\n    lag12Hours = lag(Trip_Count, 12),\n    lag1day = lag(Trip_Count, 24)\n  ) %>%\n  ungroup()\n\n# Remove rows with NA lags (first 24 hours for each station)\nstudy_panel_completeQ2 <- study_panelQ2 %>%\n  filter(!is.na(lag1day))\n\ncat(\"Rows after removing NA lags:\", format(nrow(study_panel_completeQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows after removing NA lags: 542,556 \n```\n\n\n:::\n:::\n\n\n## Visualize Lag Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample one station to visualize\nexample_station <- study_panel_completeQ2 %>%\n  filter(start_station == first(start_station)) %>%\n  head(168)  # One week\n\n# Plot actual vs lagged demand\nggplot(example_station, aes(x = interval60)) +\n  geom_line(aes(y = Trip_Count, color = \"Current\"), linewidth = 1) +\n  geom_line(aes(y = lag1Hour, color = \"1 Hour Ago\"), linewidth = 1, alpha = 0.7) +\n  geom_line(aes(y = lag1day, color = \"24 Hours Ago\"), linewidth = 1, alpha = 0.7) +\n  scale_color_manual(values = c(\n    \"Current\" = \"#08519c\",\n    \"1 Hour Ago\" = \"#3182bd\",\n    \"24 Hours Ago\" = \"#6baed6\"\n  )) +\n  labs(\n    title = \"Temporal Lag Patterns at One Station\",\n    subtitle = \"Past demand predicts future demand\",\n    x = \"Date-Time\",\n    y = \"Trip Count\",\n    color = \"Time Period\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/lag_correlations-1.png){width=672}\n:::\n:::\n\n\n# TEMPORAL TRAIN/TEST SPLIT\n\n**CRITICAL:** We must train on PAST data and test on FUTURE data!\n\n## Why Temporal Validation Matters\n\nIn real operations, at 6:00 AM on June 15, we need to predict demand for June 15-31. We have data from April 1 - June 14, but NOT from June 15-31 (it hasn't happened yet!).\n\n**Wrong approach:** Train on weeks 10-13, test on weeks 1-9 (predicting past from future!)\n\n**Correct approach:** Train on weeks 1-9, test on weeks 10-13 (predicting future from past)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split by week\n# Q2 has weeks 1-13 (Apr-Jun)\n# Train on weeks 1-9 (Apr 1 - early June)\n# Test on weeks 10-13 (rest of June)\n\n# Which stations have trips in BOTH early and late periods?\nearly_stationsQ2 <- study_panel_completeQ2 %>%\n  filter(week < 23) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\nlate_stationsQ2 <- study_panel_completeQ2 %>%\n  filter(week >= 23) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\n# Keep only stations that appear in BOTH periods\ncommon_stationsQ2 <- intersect(early_stationsQ2, late_stationsQ2)\n\n\n# Filter panel to only common stations\nstudy_panel_completeQ2 <- study_panel_completeQ2 %>%\n  filter(start_station %in% common_stationsQ2)\n\n# NOW create train/test split\ntrainQ2 <- study_panel_completeQ2 %>%\n  filter(week < 23)\n\ntestQ2 <- study_panel_completeQ2 %>%\n  filter(week >= 23)\n\ncat(\"Training observations:\", format(nrow(trainQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining observations: 374,745 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing observations:\", format(nrow(testQ2), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting observations: 161,352 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Training date range:\", min(trainQ2$date), \"to\", max(trainQ2$date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining date range: 20180 to 20242 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing date range:\", min(testQ2$date), \"to\", max(testQ2$date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting date range: 20243 to 20269 \n```\n\n\n:::\n:::\n\n\n#BUILD PREDICTIVE MODELS\n\nWe'll build 5 models with increasing complexity to see what improves predictions.\n\n## Model 1: Baseline (Time + Weather)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create day of week factor with treatment (dummy) coding\ntrainQ2 <- trainQ2 %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(trainQ2$dotw_simple) <- contr.treatment(7)\n\n# Now run the model\nmodel1Q2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation,\n  data = trainQ2\n)\n\nsummary(model1Q2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation, data = trainQ2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.6562 -0.6692 -0.2075  0.1903 25.4970 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)       -0.5694496  0.0163333 -34.864 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0449238  0.0129597  -3.466             0.000527 ***\nas.factor(hour)2  -0.0562230  0.0129656  -4.336   0.0000144932615078 ***\nas.factor(hour)3  -0.0981099  0.0129766  -7.561   0.0000000000000402 ***\nas.factor(hour)4  -0.0769564  0.0129972  -5.921   0.0000000032028721 ***\nas.factor(hour)5   0.0169165  0.0130107   1.300             0.193533    \nas.factor(hour)6   0.2382313  0.0129729  18.364 < 0.0000000000000002 ***\nas.factor(hour)7   0.4957298  0.0129839  38.180 < 0.0000000000000002 ***\nas.factor(hour)8   0.8555066  0.0129935  65.841 < 0.0000000000000002 ***\nas.factor(hour)9   0.6427567  0.0130189  49.371 < 0.0000000000000002 ***\nas.factor(hour)10  0.5230044  0.0129896  40.263 < 0.0000000000000002 ***\nas.factor(hour)11  0.5628382  0.0129568  43.440 < 0.0000000000000002 ***\nas.factor(hour)12  0.5976146  0.0129259  46.234 < 0.0000000000000002 ***\nas.factor(hour)13  0.6213231  0.0129090  48.131 < 0.0000000000000002 ***\nas.factor(hour)14  0.6515682  0.0129023  50.500 < 0.0000000000000002 ***\nas.factor(hour)15  0.7328118  0.0129094  56.766 < 0.0000000000000002 ***\nas.factor(hour)16  0.8936546  0.0129201  69.168 < 0.0000000000000002 ***\nas.factor(hour)17  1.1998470  0.0129370  92.745 < 0.0000000000000002 ***\nas.factor(hour)18  0.9581642  0.0129533  73.970 < 0.0000000000000002 ***\nas.factor(hour)19  0.6713771  0.0129564  51.818 < 0.0000000000000002 ***\nas.factor(hour)20  0.4201018  0.0129549  32.428 < 0.0000000000000002 ***\nas.factor(hour)21  0.2691135  0.0129469  20.786 < 0.0000000000000002 ***\nas.factor(hour)22  0.1825159  0.0129260  14.120 < 0.0000000000000002 ***\nas.factor(hour)23  0.0799168  0.0129103   6.190   0.0000000006016142 ***\ndotw_simple2       0.0317335  0.0069659   4.556   0.0000052270279664 ***\ndotw_simple3      -0.0075516  0.0069588  -1.085             0.277842    \ndotw_simple4       0.0517713  0.0069194   7.482   0.0000000000000733 ***\ndotw_simple5      -0.0266000  0.0069313  -3.838             0.000124 ***\ndotw_simple6      -0.0461225  0.0069325  -6.653   0.0000000000287420 ***\ndotw_simple7      -0.0767486  0.0069135 -11.101 < 0.0000000000000002 ***\nTemperature        0.0123293  0.0002031  60.710 < 0.0000000000000002 ***\nPrecipitation     -0.8122031  0.0940575  -8.635 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.133 on 374713 degrees of freedom\nMultiple R-squared:  0.1122,\tAdjusted R-squared:  0.1122 \nF-statistic:  1528 on 31 and 374713 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\nThe model uses Monday as the baseline. Each coefficient represents the difference in expected trips per station-hour compared to Monday - dow_simple2 = Tuesday..\n\n**Weekday Pattern (Tue-Fri):**\n\n-   Weekdays varying directions of coefficients (-0.027 to 0.052)\n-   Thursday has the greatest weekday effect (+0.052)\n-   Wednesday and Friday have negative coefficients. Friday may have negatives because many offices have Fridays as work-from-home days. Wednesdays, on the other hand, I'm not sure.\n\n**Weekend Pattern (Sat-Sun):**\n\n-   Both weekend days have negative coefficients (-0.046 and -0.077)\n-   This means FEWER trips per station-hour than Monday\n\n**Hourly Interpretation**\n\nHour Coefficient Interpretation: - 0 (baseline) 0.000 trips/hour (midnight) - 1am -0.045 slightly fewer than midnight ... - 6am +0.238 morning activity starting - 7am +0.496 morning rush building - 8am +0.856 PEAK morning rush - 9am +0.643 post-rush ... - 17 (5pm) +1.200 PEAK evening rush (5 PM!) - 18 (6pm) +0.958 evening declining ... - 23 (11pm) +0.080 late night minimal\n\n**Weather Interpretation** Weather Coefficient Interpretation - Temperature 0.012 with each increased degree f, trips increase by a little bit - Precipitation -0.812 when it rains, Indego trips are greatly negatively impacted\n\nFor the first model just including day of the week and weather, the R\\^2 is very low at just 0.112, meaning the model only explains 11.2% of the variation in trip counts.\n\n## Model 2: Add Temporal Lags\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2Q2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day,\n  data = trainQ2\n)\n\nsummary(model2Q2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day, data = trainQ2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.7469  -0.4742  -0.1334   0.1107  20.6374 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)       -0.2748838  0.0144790 -18.985 < 0.0000000000000002 ***\nas.factor(hour)1   0.0023600  0.0114664   0.206             0.836934    \nas.factor(hour)2   0.0204115  0.0114744   1.779             0.075260 .  \nas.factor(hour)3   0.0052515  0.0114880   0.457             0.647576    \nas.factor(hour)4   0.0383352  0.0115089   3.331             0.000866 ***\nas.factor(hour)5   0.1094577  0.0115225   9.499 < 0.0000000000000002 ***\nas.factor(hour)6   0.2564434  0.0114988  22.302 < 0.0000000000000002 ***\nas.factor(hour)7   0.3929894  0.0115282  34.089 < 0.0000000000000002 ***\nas.factor(hour)8   0.5911546  0.0115814  51.044 < 0.0000000000000002 ***\nas.factor(hour)9   0.3067783  0.0115947  26.458 < 0.0000000000000002 ***\nas.factor(hour)10  0.2481037  0.0115266  21.524 < 0.0000000000000002 ***\nas.factor(hour)11  0.2698890  0.0115037  23.461 < 0.0000000000000002 ***\nas.factor(hour)12  0.3172439  0.0114707  27.657 < 0.0000000000000002 ***\nas.factor(hour)13  0.3397462  0.0114612  29.643 < 0.0000000000000002 ***\nas.factor(hour)14  0.3503638  0.0114597  30.574 < 0.0000000000000002 ***\nas.factor(hour)15  0.3995229  0.0114756  34.815 < 0.0000000000000002 ***\nas.factor(hour)16  0.4961756  0.0115091  43.112 < 0.0000000000000002 ***\nas.factor(hour)17  0.6815436  0.0115846  58.832 < 0.0000000000000002 ***\nas.factor(hour)18  0.4079316  0.0115997  35.168 < 0.0000000000000002 ***\nas.factor(hour)19  0.2295470  0.0115457  19.882 < 0.0000000000000002 ***\nas.factor(hour)20  0.0747407  0.0115364   6.479      0.0000000000926 ***\nas.factor(hour)21  0.0488417  0.0114915   4.250      0.0000213582063 ***\nas.factor(hour)22  0.0504352  0.0114482   4.406      0.0000105565134 ***\nas.factor(hour)23  0.0197516  0.0114235   1.729             0.083805 .  \ndotw_simple2       0.0107930  0.0061630   1.751             0.079905 .  \ndotw_simple3      -0.0407980  0.0061599  -6.623      0.0000000000352 ***\ndotw_simple4       0.0256927  0.0061221   4.197      0.0000270900484 ***\ndotw_simple5      -0.0376587  0.0061340  -6.139      0.0000000008292 ***\ndotw_simple6      -0.0357403  0.0061341  -5.826      0.0000000056655 ***\ndotw_simple7      -0.0600312  0.0061179  -9.812 < 0.0000000000000002 ***\nTemperature        0.0046459  0.0001814  25.611 < 0.0000000000000002 ***\nPrecipitation     -0.3848387  0.0832409  -4.623      0.0000037800647 ***\nlag1Hour           0.2569765  0.0015748 163.175 < 0.0000000000000002 ***\nlag3Hours          0.1212182  0.0015414  78.642 < 0.0000000000000002 ***\nlag1day            0.2515002  0.0015404 163.272 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.003 on 374710 degrees of freedom\nMultiple R-squared:  0.3052,\tAdjusted R-squared:  0.3051 \nF-statistic:  4841 on 34 and 374710 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n**Question:** Did adding lags improve R²? Why or why not?\n\nAdding temporal lags improved the R\\^2 drastically from 0.112 up to 0.305.\n\nOf the three temporal lag variables, lag1Hour and lag1day have the greatest coefficients of 0.257 and 0.251 respectively. This suggests that the amount of trips at a station an hour prior and a day prior are strongly correlated to the trip count at a given station-time.\n\n## Model 3: Add Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3Q2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day +\n    Med_Inc + Percent_Taking_Transit + Percent_White,\n  data = trainQ2\n)\n\nsummary(model3Q2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day + Med_Inc + \n    Percent_Taking_Transit + Percent_White, data = trainQ2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.1529  -0.4730  -0.1387   0.1757  20.8838 \n\nCoefficients:\n                             Estimate     Std. Error t value\n(Intercept)            -0.41415352335  0.01594987822 -25.966\nas.factor(hour)1       -0.00037924054  0.01141451895  -0.033\nas.factor(hour)2        0.01561727720  0.01142267942   1.367\nas.factor(hour)3       -0.00149091347  0.01143653590  -0.130\nas.factor(hour)4        0.03076766667  0.01145747881   2.685\nas.factor(hour)5        0.10286282571  0.01147091778   8.967\nas.factor(hour)6        0.25313590484  0.01144683997  22.114\nas.factor(hour)7        0.39542379802  0.01147609337  34.456\nas.factor(hour)8        0.60177389894  0.01153035650  52.190\nas.factor(hour)9        0.32190801376  0.01154513276  27.883\nas.factor(hour)10       0.26208671470  0.01147689344  22.836\nas.factor(hour)11       0.28717773198  0.01145537278  25.069\nas.factor(hour)12       0.33217579500  0.01142157665  29.083\nas.factor(hour)13       0.35380112236  0.01141181401  31.003\nas.factor(hour)14       0.36558532918  0.01141072590  32.039\nas.factor(hour)15       0.41654118263  0.01142730011  36.451\nas.factor(hour)16       0.51646402564  0.01146223255  45.058\nas.factor(hour)17       0.70782011008  0.01154086033  61.332\nas.factor(hour)18       0.43589577308  0.01155701624  37.717\nas.factor(hour)19       0.25363399210  0.01150076886  22.054\nas.factor(hour)20       0.09661107983  0.01149020902   8.408\nas.factor(hour)21       0.06341305781  0.01144216206   5.542\nas.factor(hour)22       0.05909262047  0.01139733262   5.185\nas.factor(hour)23       0.02344743586  0.01137195778   2.062\ndotw_simple2            0.01201213287  0.00613516900   1.958\ndotw_simple3           -0.03910147692  0.00613206782  -6.377\ndotw_simple4            0.02721629029  0.00609445117   4.466\ndotw_simple5           -0.03718770698  0.00610618592  -6.090\ndotw_simple6           -0.03648222656  0.00610635524  -5.974\ndotw_simple7           -0.06111598669  0.00609020146 -10.035\nTemperature             0.00509680286  0.00018074353  28.199\nPrecipitation          -0.41301316345  0.08286532019  -4.984\nlag1Hour                0.24575879010  0.00157940667 155.602\nlag3Hours               0.10860074664  0.00154951449  70.087\nlag1day                 0.23901775691  0.00154818341 154.386\nMed_Inc                 0.00000061131  0.00000006125   9.981\nPercent_Taking_Transit -0.00258793144  0.00018899806 -13.693\nPercent_White           0.00246691765  0.00009675471  25.497\n                                   Pr(>|t|)    \n(Intercept)            < 0.0000000000000002 ***\nas.factor(hour)1                    0.97350    \nas.factor(hour)2                    0.17156    \nas.factor(hour)3                    0.89628    \nas.factor(hour)4                    0.00725 ** \nas.factor(hour)5       < 0.0000000000000002 ***\nas.factor(hour)6       < 0.0000000000000002 ***\nas.factor(hour)7       < 0.0000000000000002 ***\nas.factor(hour)8       < 0.0000000000000002 ***\nas.factor(hour)9       < 0.0000000000000002 ***\nas.factor(hour)10      < 0.0000000000000002 ***\nas.factor(hour)11      < 0.0000000000000002 ***\nas.factor(hour)12      < 0.0000000000000002 ***\nas.factor(hour)13      < 0.0000000000000002 ***\nas.factor(hour)14      < 0.0000000000000002 ***\nas.factor(hour)15      < 0.0000000000000002 ***\nas.factor(hour)16      < 0.0000000000000002 ***\nas.factor(hour)17      < 0.0000000000000002 ***\nas.factor(hour)18      < 0.0000000000000002 ***\nas.factor(hour)19      < 0.0000000000000002 ***\nas.factor(hour)20      < 0.0000000000000002 ***\nas.factor(hour)21            0.000000029915 ***\nas.factor(hour)22            0.000000216386 ***\nas.factor(hour)23                   0.03922 *  \ndotw_simple2                        0.05024 .  \ndotw_simple3                 0.000000000181 ***\ndotw_simple4                 0.000007981231 ***\ndotw_simple5                 0.000000001129 ***\ndotw_simple6                 0.000000002310 ***\ndotw_simple7           < 0.0000000000000002 ***\nTemperature            < 0.0000000000000002 ***\nPrecipitation                0.000000622625 ***\nlag1Hour               < 0.0000000000000002 ***\nlag3Hours              < 0.0000000000000002 ***\nlag1day                < 0.0000000000000002 ***\nMed_Inc                < 0.0000000000000002 ***\nPercent_Taking_Transit < 0.0000000000000002 ***\nPercent_White          < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9981 on 374707 degrees of freedom\nMultiple R-squared:  0.3115,\tAdjusted R-squared:  0.3114 \nF-statistic:  4581 on 37 and 374707 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\nAdding demographic data only increased the R\\^2 from 0.305 to 0.311\n\nPercent_Taking_Transit and Percent_White had coefficients of -0.0026 and 0.0025. Each additional percent of the station tract's population taking transit or being white only correlated with the station-hour trip count increase or decrease by 0.0025.\n\nThe demographic variables we added don't seem to improve our model's fit by much.\n\n## Model 4: Add Station Fixed Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4Q2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    as.factor(start_station),\n  data = trainQ2\n)\n\n# Summary too long with all station dummies, just show key metrics\ncat(\"Model 4 R-squared:\", summary(model4Q2)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 R-squared: 0.3369023 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 4 Adj R-squared:\", summary(model4Q2)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 Adj R-squared: 0.3364029 \n```\n\n\n:::\n:::\n\n\nThe R\\^2 increased from 0.311 to 0.336 from the last model with the addition of station fixed effects.\n\n**What do station fixed effects capture?** Baseline differences in demand across stations (some are just busier than others!).\n\n## Model 5: Add Rush Hour Interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel5Q2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day + rush_hour + as.factor(month) +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    as.factor(start_station) +\n    rush_hour * weekend,  # Rush hour effects different on weekends\n  data = trainQ2\n)\n\ncat(\"Model 5 R-squared:\", summary(model5Q2)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 R-squared: 0.3407678 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 5 Adj R-squared:\", summary(model5Q2)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 Adj R-squared: 0.3402661 \n```\n\n\n:::\n:::\n\n\nOur 5th model with rush hour interactions added is our best-fitting one so far. With an adjusted R\\^2 of 0.340, it accounts for 34% of the variation in trip counts at the station-hour. That being said, adding the rush hour interaction only improved the R\\^2 by 0.04 (or 4%).\n\n# MODEL EVALUATION\n\n## Calculate Predictions and MAE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get predictions on test set\n\n# Create day of week factor with treatment (dummy) coding\ntestQ2 <- testQ2 %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(testQ2$dotw_simple) <- contr.treatment(7)\n\ntestQ2 <- testQ2 %>%\n  mutate(\n    pred1Q2 = predict(model1Q2, newdata = testQ2),\n    pred2Q2 = predict(model2Q2, newdata = testQ2),\n    pred3Q2 = predict(model3Q2, newdata = testQ2),\n    pred4Q2 = predict(model4Q2, newdata = testQ2),\n    pred5Q2 = predict(model5Q2, newdata = testQ2)\n  )\n\n# Calculate MAE for each model\nmae_resultsQ2 <- data.frame(\n  Model = c(\n    \"1. Time + Weather\",\n    \"2. + Temporal Lags\",\n    \"3. + Demographics\",\n    \"4. + Station FE\",\n    \"5. + Rush Hour Interaction\"\n  ),\n  MAE = c(\n    mean(abs(testQ2$Trip_Count - testQ2$pred1Q2), na.rm = TRUE),\n    mean(abs(testQ2$Trip_Count - testQ2$pred2Q2), na.rm = TRUE),\n    mean(abs(testQ2$Trip_Count - testQ2$pred3Q2), na.rm = TRUE),\n    mean(abs(testQ2$Trip_Count - testQ2$pred4Q2), na.rm = TRUE),\n    mean(abs(testQ2$Trip_Count - testQ2$pred5Q2), na.rm = TRUE)\n  )\n)\n\nkable(mae_resultsQ2, \n      digits = 2,\n      caption = \"Mean Absolute Error by Model (Test Set)\",\n      col.names = c(\"Model\", \"MAE (trips)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. Time + Weather </td>\n   <td style=\"text-align:right;\"> 0.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> 0.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. + Demographics </td>\n   <td style=\"text-align:right;\"> 0.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4. + Station FE </td>\n   <td style=\"text-align:right;\"> 0.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. + Rush Hour Interaction </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Visualize Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mae_resultsQ2, aes(x = reorder(Model, -MAE), y = MAE)) +\n  geom_col(fill = \"#3182bd\", alpha = 0.8) +\n  geom_text(aes(label = round(MAE, 2)), vjust = -0.5) +\n  labs(\n    title = \"Model Performance Comparison\",\n    subtitle = \"Lower MAE = Better Predictions\",\n    x = \"Model\",\n    y = \"Mean Absolute Error (trips)\"\n  ) +\n  plotTheme +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/compare_models-1.png){width=672}\n:::\n:::\n\n\n**Question:** Which features gave us the biggest improvement?\n\nOur best predicting model is Model 4 which includes DOTW, Hour, Time, Weather, Temporal Lags, Demographics, and Station FE, and Rush Hour Interaction with an MAE of 0.69. The best improvements of MAE between models was between models 1 and 2, suggesting temporal lags made the biggest difference in predictive power.\n\nAdding temporal lags to the model improved the MAE the most (0.84 to 0.69). All other added variables improved the model by -0.01 MAE or less. The Rush hour interaction actually worsened the MAE from 0.69 to 0.71.\n\n# SPACE-TIME ERROR ANALYSIS\n\n## Observed vs. Predicted\n\nLet's use our best model (Model 4) for error analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntestQ2 <- testQ2 %>%\n  mutate(\n    error = Trip_Count - pred4Q2,\n    abs_error = abs(error),\n    time_of_day = case_when(\n      hour < 7 ~ \"Overnight\",\n      hour >= 7 & hour < 10 ~ \"AM Rush\",\n      hour >= 10 & hour < 15 ~ \"Mid-Day\",\n      hour >= 15 & hour <= 18 ~ \"PM Rush\",\n      hour > 18 ~ \"Evening\"\n    )\n  )\n\n# Scatter plot by time and day type\nggplot(testQ2, aes(x = Trip_Count, y = pred4Q2)) +\n  geom_point(alpha = 0.2, color = \"#3182bd\") +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", linewidth = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +\n  facet_grid(weekend ~ time_of_day) +\n  labs(\n    title = \"Observed vs. Predicted Bike Trips\",\n    subtitle = \"Model 4 performance by time period\",\n    x = \"Observed Trips\",\n    y = \"Predicted Trips\",\n    caption = \"Red line = perfect predictions; Green line = actual model fit\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/obs_vs_pred-1.png){width=672}\n:::\n:::\n\n\n**Question:** Where is the model performing well? Where is it struggling?\n\nThe model performs best in the evening and at the PM rush. Its worst performance in general is overnight and mid-day.\n\n## Spatial Error Patterns\n\nAre prediction errors clustered in certain parts of Philadelphia?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MAE by station\nstation_errorsQ2 <- testQ2 %>%\n  group_by(start_station, start_lat, start_lon) %>%\n  summarize(\n    MAE = mean(abs_error, na.rm = TRUE),\n    avg_demand = mean(Trip_Count, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  filter(!is.na(start_lat), !is.na(start_lon))\n\n## Create Two Maps Side-by-Side with Proper Legends (sorry these maps are ugly)\n\n# Calculate station errors\nstation_errorsQ2 <- testQ2 %>%\n  filter(!is.na(pred4Q2)) %>%\n  group_by(start_station, start_lat, start_lon) %>%\n  summarize(\n    MAE = mean(abs(Trip_Count - pred2Q2), na.rm = TRUE),\n    avg_demand = mean(Trip_Count, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  filter(!is.na(start_lat), !is.na(start_lon))\n\n# Map 1: Prediction Errors\np1 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.2) +\n  geom_point(\n    data = station_errorsQ2,\n    aes(x = start_lon, y = start_lat, color = MAE),\n    size = 3.5,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"plasma\",\n    name = \"MAE\\n(trips)\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5),  # Fewer, cleaner breaks\n    labels = c(\"0.5\", \"1.0\", \"1.5\")\n  ) +\n  labs(title = \"Prediction Errors\",\n       subtitle = \"Higher in Center City\") +\n  mapTheme +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 1.5,\n    barheight = 12,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\n# Map 2: Average Demand\np2 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.2) +\n  geom_point(\n    data = station_errorsQ2,\n    aes(x = start_lon, y = start_lat, color = avg_demand),\n    size = 3.5,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"viridis\",\n    name = \"Avg\\nDemand\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5, 2.0, 2.5),  # Clear breaks\n    labels = c(\"0.5\", \"1.0\", \"1.5\", \"2.0\", \"2.5\")\n  ) +\n  labs(title = \"Average Demand\",\n       subtitle = \"Trips per station-hour\") +\n  mapTheme +\n  theme(\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 1.5,\n    barheight = 12,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\n\n\n\n# Map 1: Prediction Errors\np1 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +\n  geom_point(\n    data = station_errorsQ2,\n    aes(x = start_lon, y = start_lat, color = MAE),\n    size = 3.5,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"plasma\",\n    name = \"MAE (trips)\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5),\n    labels = c(\"0.5\", \"1.0\", \"1.5\")\n  ) +\n  labs(title = \"Prediction Errors\") +\n  mapTheme +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 12,\n    barheight = 1,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\n# Map 2: Average Demand  \np2 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +\n  geom_point(\n    data = station_errorsQ2,\n    aes(x = start_lon, y = start_lat, color = avg_demand),\n    size = 3.5,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"viridis\",\n    name = \"Avg Demand (trips/hour)\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5, 2.0, 2.5),\n    labels = c(\"0.5\", \"1.0\", \"1.5\", \"2.0\", \"2.5\")\n  ) +\n  labs(title = \"Average Demand\") +\n  mapTheme +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 12,\n    barheight = 1,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\n# Combine\n(p1 | p2)\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/spatial_errors-1.png){width=672}\n:::\n:::\n\n\n**Question:** Do you see spatial clustering of errors? What neighborhoods have high errors?\n\nCenter City on average has higher errors than most parts of the city. West Philly and North Philly seem to have clusters of low error. Greatest demand seems to have nearly identical spatial distribution as error in Philadelphia, meaning areas of greater average demand have greater prediction error\n\n## Temporal Error Patterns\n\nWhen are we most wrong?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MAE by time of day and day type\ntemporal_errorsQ2 <- testQ2 %>%\n  group_by(time_of_day, weekend) %>%\n  summarize(\n    MAE = mean(abs_error, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(day_type = ifelse(weekend == 1, \"Weekend\", \"Weekday\"))\n\nggplot(temporal_errorsQ2, aes(x = time_of_day, y = MAE, fill = day_type)) +\n  geom_col(position = \"dodge\") +\n  scale_fill_manual(values = c(\"Weekday\" = \"#08519c\", \"Weekend\" = \"#6baed6\")) +\n  labs(\n    title = \"Prediction Errors by Time Period\",\n    subtitle = \"When is the model struggling most?\",\n    x = \"Time of Day\",\n    y = \"Mean Absolute Error (trips)\",\n    fill = \"Day Type\"\n  ) +\n  plotTheme +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/temporal_errors-1.png){width=672}\n:::\n:::\n\n\nContrary to the written analysis from the Observed vs Predicted bike trips figure, th Overnight hours have the least error, and the PM rush has the worst. It looks like predictions during the least busy times do the best, and predictions during the busiest times do the worst.\n\n## Errors and Demographics\n\nAre prediction errors related to neighborhood characteristics?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join demographic data to station errors\nstation_errors_demoQ2 <- station_errorsQ2 %>%\n  left_join(\n    station_attributesQ2 %>% select(start_station, Med_Inc, Percent_Taking_Transit, Percent_White),\n    by = \"start_station\"\n  ) %>%\n  filter(!is.na(Med_Inc))\n\n# Create plots\np1 <- ggplot(station_errors_demoQ2, aes(x = Med_Inc, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  scale_x_continuous(labels = scales::dollar) +\n  labs(title = \"Errors vs. Median Income\", x = \"Median Income\", y = \"MAE\") +\n  plotTheme\n\np2 <- ggplot(station_errors_demoQ2, aes(x = Percent_Taking_Transit, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(title = \"Errors vs. Transit Usage\", x = \"% Taking Transit\", y = \"MAE\") +\n  plotTheme\n\np3 <- ggplot(station_errors_demoQ2, aes(x = Percent_White, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(title = \"Errors vs. Race\", x = \"% White\", y = \"MAE\") +\n  plotTheme\n\n(p1 | p2) / (p3 | plot_spacer())\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/errors_demographics-1.png){width=672}\n:::\n:::\n\n\n**Critical Question:** Are prediction errors systematically higher in certain demographic groups? What are the equity implications?\n\nYes.Our model performs the best (lower MAE) where median income is lower, % white is lower, and % taking transit is higher. On the flipside, it struggles to predict trips in census tracts where median income is greater, % white is greater, and % taking transit is smaller.\n\nIn other words, our model is less effective in wealthier, whiter neighborhoods where fewer people take transit.\n",
    "supporting": [
      "lab_5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}