project:
  type: website
  output-dir: docs

website:
  title: "Indrajeet Chavan - CPLN 5920 Portfolio"
  navbar:          # 👈 indentation matters
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: Labs/Labs_0/lab0_IC.qmd
            text: "Lab 0: dplyr Basics"
          - href: Labs/Labs_1/lab1_IC.qmd
            text: "Lab 1: Census Data Exploration"
          - href: Labs/Labs_2/lab2_IC.qmd
            text: "Lab 2: Spatial Analysis and Visualization"
          - href: Labs/Labs_3/Chavan_Indrajeet_Appendix.qmd
            text: "Lab 3: Philadelphia Housing Price Prediction Model (Technical Appendix)"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
