{
  "hash": "6ea31a24d4946658882110aa21bf948f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: Indrajeet Chavan\ndate: February 23, 2026\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n#Clearing previous data\nrm(list=ls())\n\n# Load required packages\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(dplyr)\nlibrary(sf)\nlibrary(tigris)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\noptions(tigris_use_cache = TRUE)\n\nsetwd(\"/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2\")\n\n# Load spatial data\npa_counties <- st_read(here(\"/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ndistricts <- st_read(here(\"/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/districts.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `U.S._Congressional_Districts_for_Pennsylvania' from data source \n  `/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/districts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 17 features and 8 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51939 ymin: 39.71986 xmax: -74.68956 ymax: 42.26935\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/indrajeetchavan/Library/CloudStorage/OneDrive-PennO365/Penn/6. Penn Sem 2/CPLN 5920 PPA/GitHub/IC_PPARep/Labs/Labs_2/Data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\nmetro_areas <- core_based_statistical_areas(cb = TRUE)\n\n# Check that all data loaded correctly\nnrow(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 223\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3445\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check CRS\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n**223 Hospitals**\n\n- How many census tracts?\n**3445 Census tracts**\n\n- What coordinate reference system is each dataset in?\n**Co ordinate systems are as follows:**\n**1. pa_counties : EPSG:3857 (WGS 84)**\n**2. hospitals : EPSG:4326 (WGS 84)**\n**3. census_tracts : EPSG:4269 (NAD83)**\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nacs_vars <- c(\n  total_pop = \"B01003_001\",\n  median_income = \"B19013_001\",\n  age_65_66 = \"B01001_020\",\n  age_67_69 = \"B01001_021\",\n  age_70_74 = \"B01001_022\",\n  age_75_79 = \"B01001_023\",\n  age_80_84 = \"B01001_024\",\n  age_85plus = \"B01001_025\",\n  age_65_66_f = \"B01001_044\",\n  age_67_69_f = \"B01001_045\",\n  age_70_74_f = \"B01001_046\",\n  age_75_79_f = \"B01001_047\",\n  age_80_84_f = \"B01001_048\",\n  age_85plus_f = \"B01001_049\"\n)\n\nacs_data <- get_acs(\n  geography = \"tract\",\n  variables = acs_vars,\n  state = \"PA\",\n  year = 2022,\n  geometry = FALSE\n)\n\n# Pivot wider\nacs_wide <- acs_data %>%\n  select(GEOID, variable, estimate) %>%\n  pivot_wider(names_from = variable, values_from = estimate)\n\n# Calculate elderly population\nacs_wide <- acs_wide %>%\n  mutate(\n    elderly_pop = age_65_66 + age_67_69 + age_70_74 +\n                  age_75_79 + age_80_84 + age_85plus +\n                  age_65_66_f + age_67_69_f + age_70_74_f +\n                  age_75_79_f + age_80_84_f + age_85plus_f,\n    elderly_pct = elderly_pop / total_pop\n  )\n\n# Join to tract boundaries\n# Join to spatial tracts\ntracts_pa <- census_tracts %>%\n  left_join(acs_wide, by = \"GEOID\")\n\n#tracts have missing income data\nsum(is.na(tracts_pa$median_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n\n```{.r .cell-code}\n#median income across all PA census tracts\nmedian(tracts_pa$median_income, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n**ACS Year: 2022 (5-year)**\n\n- How many tracts have missing income data?\n**62 Census Tracts**\n\n- What is the median income across all PA census tracts?\n**70188**\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n#Income Threshold: Low Income groups below median income of PA\nstate_median_income <- median(tracts_pa$median_income, na.rm = TRUE)\n\n#Vulnerable Population: Low Income groups below median income of PA & high elderly population\nvulnerable_tracts <- tracts_pa %>%\n  mutate(\n    low_income = median_income < state_median_income,\n    high_elderly = elderly_pct >= 0.15,\n    vulnerable = low_income & high_elderly\n  )\n\n#Count of Vulnerable tracts\nsum(vulnerable_tracts$vulnerable, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1125\n```\n\n\n:::\n\n```{.r .cell-code}\n#percentage of PA census tracts are considered vulnerable\nmean(vulnerable_tracts$vulnerable, na.rm = TRUE) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.02025\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n**Low income groups with income below PA median income value**\n\n- What elderly population threshold did you choose and why?\n**High elderly population determined by tracts with ≥ 15% population age 65+**\n\n- How many tracts meet your vulnerability criteria?\n**1125 Census Tracts**\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n**33.02025 % tracts**\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n#Using Pennsylvania South State Plane:EPSG: 32129 (good for distance in meters)\n\n# Transform\ntracts_proj <- st_transform(vulnerable_tracts, 32129)\nhospitals_proj <- st_transform(hospitals, 32129)\n\n# Get centroids\ntract_centroids <- st_centroid(tracts_proj)\n\n# Calculate distance from each tract centroid to nearest hospital\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\n\nnearest_dist <- apply(dist_matrix, 1, min)\n\n# Convert meters to miles\ntracts_proj$dist_miles <- as.numeric(nearest_dist) / 1609.34\n\n#Separating vulnerable tracts\nvulnerable_only <- tracts_proj %>%\n  filter(vulnerable == TRUE)\n\n#Finding the distance stats\nmean(vulnerable_only$dist_miles, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.310786\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(vulnerable_only$dist_miles, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 29.11601\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(vulnerable_only$dist_miles > 15, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**We are using the Pennsylvania South State Plane:EPSG: 32129 as it is good for calculating distance in meters which can be later converted into miles.**\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n**5.310786 miles**\n\n- What is the maximum distance?\n**29.11601 miles**\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n**64 Tracts**\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\ntracts_proj <- tracts_proj %>%\n  mutate(underserved = vulnerable & dist_miles > 15)\n\n#Number of tracts that are underserved\nsum(tracts_proj$underserved, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64\n```\n\n\n:::\n\n```{.r .cell-code}\n#percentage of vulnerable tracts that are underserved\nmean(tracts_proj$underserved[tracts_proj$vulnerable], na.rm = TRUE) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.688889\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n**64 tracts**\n\n- What percentage of vulnerable tracts are underserved?\n**5.688889 %**\n\n- Does this surprise you? Why or why not?\n**Not entirely as at first glance, 5.7% seems small. I would expect a much larger share of vulnerable tracts to be far from hospitals, especially in a state as geographically large as Pennsylvania. However, there are a few reasons this percentage makes sense. The reasons include:**\n**1. Pennsylvania Has Strong Hospital Coverage**\n**2. Vulnerability and long-distance access don’t always overla**\n**3. Fifteen miles is a fairly large service radius**\n**4. Though small, the percentage can still represent a huge population based on which tracts come under these tracts.**\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n\n# Transform counties\ncounties_proj <- st_transform(pa_counties, 32129)\n\n# Spatial join\ntracts_county <- st_join(tracts_proj, counties_proj)\n\n#highest percentage of underserved vulnerable tracts\ncounty_summary <- tracts_county %>%\n  st_drop_geometry() %>%\n  group_by(NAMELSADCO) %>%\n  summarise(\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = underserved_tracts / vulnerable_tracts,\n    avg_dist = mean(dist_miles[vulnerable], na.rm = TRUE),\n    total_vulnerable_pop = sum(elderly_pop[vulnerable], na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\n#the most vulnerable people living far from hospitals\ncounty_summary <- tracts_county %>%\n  st_drop_geometry() %>%\n  group_by(NAMELSADCO) %>%\n  summarise(\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = underserved_tracts / vulnerable_tracts,\n    avg_dist = mean(dist_miles[vulnerable], na.rm = TRUE),\n    total_vulnerable_pop = sum(elderly_pop[vulnerable], na.rm = TRUE)\n  ) %>%\n  arrange(desc(total_vulnerable_pop))\n\n# Aggregate statistics by county\nhead(county_summary, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  NAMELSADCO       vulnerable_tracts underserved_tracts pct_underserved avg_dist\n  <chr>                        <int>              <int>           <dbl>    <dbl>\n1 Philadelphia Co…               111                  0               0     1.31\n2 Allegheny County               148                  0               0     2.56\n3 Westmoreland Co…                85                  0               0     4.90\n4 Luzerne County                  59                  0               0     4.56\n5 Cambria County                  52                  0               0     6.29\n# ℹ 1 more variable: total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n**The counties that have the highest percentage of underserved vulnerable tracts are Cameron County, Forest County, Sullivan County, Pike County and Snyder County.**\n\n- Which counties have the most vulnerable people living far from hospitals?\n**The counties that have the most vulnerable people living far from hospitals are Philadelphia County, Allegheny County, Westmoreland County, Luzerne County and Cambria County.**\n\n- Are there any patterns in where underserved counties are located?\n**There is a clear spatial pattern in the distribution of underserved counties. Counties with the highest percentage of underserved vulnerable tracts are predominantly rural with low population density. These areas likely face structural healthcare access challenges due to limited hospital infrastructure and large geographic distances. In contrast, counties with the greatest number of vulnerable residents living far from hospitals are highly populated urban counties such as Philadelphia and Allegheny. Thus high absolute numbers of vulnerable residents affected. We see rural spatial isolation and urban scale-based disparities.**\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\n\npriority_table <- county_summary %>%\n  slice_max(pct_underserved, n = 10)\n\nkable(priority_table,\n      caption = \"Top 10 Priority Counties for Healthcare Investment\",\n      digits = 2)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment\n\n|NAMELSADCO        | vulnerable_tracts| underserved_tracts| pct_underserved| avg_dist| total_vulnerable_pop|\n|:-----------------|-----------------:|------------------:|---------------:|--------:|--------------------:|\n|Forest County     |                 8|                  8|            1.00|    18.40|                 6372|\n|Cameron County    |                 7|                  7|            1.00|    19.35|                 5474|\n|Sullivan County   |                 9|                  9|            1.00|    20.31|                 3700|\n|Pike County       |                11|                  8|            0.73|    17.40|                 5423|\n|Snyder County     |                17|                 12|            0.71|    16.11|                18298|\n|Juniata County    |                15|                 10|            0.67|    15.34|                11988|\n|Clearfield County |                31|                 13|            0.42|    14.07|                24894|\n|Union County      |                11|                  4|            0.36|    12.25|                 8487|\n|Dauphin County    |                22|                  7|            0.32|     8.58|                15255|\n|Centre County     |                16|                  5|            0.31|    10.40|                11247|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nc1 <- c(\"COUNTY_NAM\", \"vulnerable_tracts\", \"undeserved_tracts\", \"pct_undeserved\", \"avg_dist\", \"total_vulnerable_pop\")\ncounty_summary <- county_summary %>%\n  mutate(colnames(c1))\n\ncounty_map <- counties_proj %>%\n  left_join(county_summary, by = c(\"COUNTY_NAM\" = \"NAMELSADCO\"))\n\n#a choropleth map showing healthcare access challenge\nggplot() +\n  geom_sf(data = county_map, aes(fill = pct_underserved), color = \"white\") +\n  geom_sf(data = hospitals_proj, size = 1, color = \"black\") +\n  scale_fill_viridis_c(labels = percent_format()) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percent of Vulnerable Tracts More Than 15 Miles from Hospital\",\n    fill = \"% Underserved\",\n    caption = \"Source: ACS 2022, Hospital Data\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_IC_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\nggplot() +\n  geom_sf(data = counties_proj, fill = NA, color = \"gray\") +\n  geom_sf(data = tracts_proj %>% filter(underserved),\n          fill = \"red\", color = NA, alpha = 0.6) +\n  geom_sf(data = hospitals_proj, size = 1) +\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Vulnerable tracts more than 15 miles from nearest hospital\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_IC_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nggplot(vulnerable_only, aes(x = dist_miles)) +\n  geom_histogram(bins = 30, color =\"white\") +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital\",\n    x = \"Distance (miles)\",\n    y = \"Number of Vulnerable Tracts\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_IC_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n```\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[Write your findings here]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_IC_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}